#Configurações do projeto

# Database configuration
spring:
  datasource:
    # Driver JDBC, banco H2, em memória
    url: jdbc:h2:mem:patrimonyDB
    username: sa
    password:
  h2:
    #Habilita o console para acesso no navegador
    console:
      enabled: true
      path: /h2-console
